# Generated by Django 3.2 on 2021-04-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('details', models.TextField(null=True)),
                ('description', models.CharField(max_length=30)),
                ('image_url', models.CharField(default='https://i.stack.imgur.com/y9DpT.jpg', max_length=400)),
                ('price', models.FloatField()),
                ('categories', models.ManyToManyField(to='store.Category')),
            ],
        ),
    ]
