# Generated by Django 3.2 on 2021-05-02 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_cart_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='totalPrice',
        ),
    ]
