# Generated by Django 5.1.6 on 2025-02-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentStatus',
            field=models.CharField(default='NOT_APPROVED', max_length=30),
        ),
    ]
