# Generated by Django 5.1.6 on 2025-02-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_order_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publicId',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
