# Generated by Django 5.1.6 on 2025-03-02 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_publicid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='publicId',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
